# Generated by Django 5.0.7 on 2024-07-23 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.RemoveField(
            model_name='project',
            name='city',
        ),
        migrations.RemoveField(
            model_name='location',
            name='city',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='publisher',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
        migrations.RemoveField(
            model_name='project',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sub_area',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='project',
            name='website',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='PropertyType',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.DeleteModel(
            name='SubArea',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Website',
        ),
    ]
