# Generated by Django 5.0.7 on 2024-07-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
