# Generated by Django 5.0.7 on 2024-07-24 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='api.category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='api.city'),
        ),
        migrations.AlterField(
            model_name='project',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_type', to='api.propertytype'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sub_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_area', to='api.subarea'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='api.subcategory'),
        ),
        migrations.AlterField(
            model_name='project',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website', to='api.website'),
        ),
    ]
