# Generated by Django 5.0.7 on 2024-07-25 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_project_publisher_apikey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIKey',
        ),
    ]
