# Generated by Django 5.0.7 on 2024-08-03 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_project_amenities_alter_project_builder_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
