# Generated by Django 5.0.7 on 2024-08-03 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_delete_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='projects/pictures/')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pictuer', to='api.project')),
            ],
        ),
    ]
