# Generated by Django 5.0.7 on 2024-08-09 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_apikey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIKey',
        ),
    ]
