# Generated by Django 5.0.7 on 2024-08-14 07:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0024_remove_project_category_remove_location_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Commercial', 'Commercial'), ('Residential', 'Residential')], default='Commercial', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('listing', models.BigAutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=255)),
                ('department', models.CharField(default='', max_length=255)),
                ('designation', models.CharField(default='', max_length=255)),
                ('role', models.CharField(default='', max_length=255)),
                ('name', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(default='', max_length=20)),
                ('password', models.CharField(default='', max_length=50)),
                ('address', models.TextField(default='')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('pub_id', models.CharField(default='', max_length=255)),
                ('listing_date', models.DateTimeField(blank=True, default='', null=True)),
                ('plan_id', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('dist', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('other', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('latitude', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='api.city')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='', null=True)),
                ('picture', models.FileField(blank=True, null=True, upload_to='projects/pictures/')),
                ('view', models.BigIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_for_rent', models.BooleanField(default=False)),
                ('title', models.TextField(default='', null=True)),
                ('amenities', models.TextField(default='', null=True)),
                ('nearby', models.TextField(default='', null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('construction_status', models.TextField(default='', null=True)),
                ('status', models.TextField(default='', null=True)),
                ('furnished', models.TextField(default='', null=True)),
                ('security_deposit', models.BigIntegerField(default=0)),
                ('rent_property', models.TextField(default='', null=True)),
                ('rent_escalation_period', models.TextField(default='', null=True)),
                ('rent_priority_comment', models.TextField(default='', null=True)),
                ('size', models.BigIntegerField(default=0)),
                ('carpet_area', models.BigIntegerField(default=0)),
                ('type', models.TextField(default='', null=True)),
                ('builder', models.TextField(default='', null=True)),
                ('floor', models.IntegerField(default=0)),
                ('total_floor', models.IntegerField(default=0)),
                ('facing', models.TextField(default='', null=True)),
                ('possession_type', models.TextField(default='', null=True)),
                ('is_rented', models.BooleanField(default=False)),
                ('rent', models.CharField(default='', max_length=50, null=True)),
                ('cost', models.BigIntegerField(default=0)),
                ('extra_charge', models.BigIntegerField(default=0)),
                ('lease_time', models.CharField(default='', max_length=20, null=True)),
                ('lease_completed', models.BooleanField(default=False)),
                ('lease_balance', models.BigIntegerField(default=0)),
                ('rent_escalation', models.TextField(default='', null=True)),
                ('rent_to', models.CharField(default='', max_length=50, null=True)),
                ('maintenance', models.CharField(default='', max_length=50, null=True)),
                ('registry', models.CharField(default='', max_length=100, null=True)),
                ('transfer_charge', models.BigIntegerField(default=0)),
                ('gst', models.BigIntegerField(default=0)),
                ('profit_sharing', models.BigIntegerField(default=0)),
                ('roi', models.TextField(default='', null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='projects/profile_pic/')),
                ('shop_for', models.TextField(default='', null=True)),
                ('posted_by', models.TextField(default='', null=True)),
                ('possession_status', models.BooleanField(default=False)),
                ('possession_date', models.DateTimeField(blank=True, null=True)),
                ('is_corner_plot', models.BooleanField(default=False)),
                ('hidden_notes', models.FileField(blank=True, null=True, upload_to='projects/hidden_notes')),
                ('lock_in', models.TextField(default='', null=True)),
                ('power_breakup_rate', models.CharField(default='', max_length=50, null=True)),
                ('road_size', models.CharField(default='', max_length=100)),
                ('meta_desc', models.TextField(default='', null=True)),
                ('meta_key', models.CharField(default='', max_length=200, null=True)),
                ('is_distress', models.BooleanField(default=False)),
                ('reason_distress', models.CharField(default='', max_length=100, null=True)),
                ('cost_distress', models.CharField(default='', max_length=50, null=True)),
                ('recommended', models.BooleanField(default=False)),
                ('plot_size', models.CharField(default='', max_length=50, null=True)),
                ('construction_age', models.CharField(default='', max_length=200, null=True)),
                ('code', models.CharField(default='', max_length=50, null=True)),
                ('listing_date', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(default='', max_length=200, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='api.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='api.location')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_type', to='api.propertytype')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to='api.publisher')),
                ('sub_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_area', to='api.subarea')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='api.subcategory')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website', to='api.website')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='projects/pictures/')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pictuer', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='api.publisher')),
            ],
        ),
    ]
