# Generated by Django 5.0.7 on 2024-08-16 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_history'),
        ('myapp', '0037_sitevisiter_csrftoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='sitevisiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.sitevisiter'),
        ),
    ]
