# Generated by Django 5.0.7 on 2024-08-16 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_history_sitevisiter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='sitevisiter',
            new_name='visiter',
        ),
    ]
