# Generated by Django 5.0.7 on 2024-08-17 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_rename_sitevisiter_history_visiter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='model_name',
            new_name='url',
        ),
    ]
