# Generated by Django 5.0.7 on 2024-08-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_rename_model_name_history_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='amenities',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='builder',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(blank=True, default='NA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='construction_age',
            field=models.CharField(blank=True, default='NA', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='construction_status',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='cost_distress',
            field=models.CharField(blank=True, default='NA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='facing',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='furnished',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='lease_time',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='listing_date',
            field=models.DateTimeField(blank=True, default='NA', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='lock_in',
            field=models.TextField(blank=True, default='NA', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='maintenance',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='meta_desc',
            field=models.TextField(blank=True, default='NA', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='meta_key',
            field=models.CharField(blank=True, default='NA', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='plot_size',
            field=models.CharField(default='NA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='possession_type',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='posted_by',
            field=models.TextField(blank=True, default='NA', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='power_breakup_rate',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='reason_distress',
            field=models.CharField(blank=True, default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='registry',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='rent',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='rent_escalation',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='rent_escalation_period',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='rent_priority_comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='rent_property',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='rent_to',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='road_size',
            field=models.CharField(blank=True, default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='roi',
            field=models.TextField(blank=True, default='NA', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='shop_for',
            field=models.TextField(blank=True, default='NA', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, default='NA', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
