# Generated by Django 5.0.7 on 2024-08-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_project_amenities_alter_project_builder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, default='NA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='dist',
            field=models.CharField(blank=True, default='NA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.CharField(blank=True, default='NA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.CharField(blank=True, default='NA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='other',
            field=models.CharField(blank=True, default='NA', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, default='NA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='amenities',
            field=models.TextField(default='NA', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='builder',
            field=models.TextField(default='NA', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(default='NA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='construction_age',
            field=models.CharField(default='NA', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='construction_status',
            field=models.TextField(default='NA', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='cost_distress',
            field=models.CharField(default='NA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='NA', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='facing',
            field=models.TextField(default='NA', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='furnished',
            field=models.TextField(default='NA', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='lease_time',
            field=models.CharField(default='NA', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='lock_in',
            field=models.TextField(default='NA', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='maintenance',
            field=models.CharField(default='NA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='meta_desc',
            field=models.TextField(default='NA', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='meta_key',
            field=models.CharField(default='NA', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='nearby',
            field=models.TextField(default='NA', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='plot_size',
            field=models.CharField(default='NA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='possession_type',
            field=models.TextField(default='NA', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='posted_by',
            field=models.TextField(default='NA', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='power_breakup_rate',
            field=models.CharField(default='NA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='reason_distress',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='registry',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='rent',
            field=models.CharField(default='NA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='rent_escalation',
            field=models.TextField(default='NA', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='rent_escalation_period',
            field=models.TextField(default='NA', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='rent_priority_comment',
            field=models.TextField(default='NA', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='rent_property',
            field=models.TextField(default='NA', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='rent_to',
            field=models.CharField(default='NA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='road_size',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='roi',
            field=models.TextField(default='NA', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='shop_for',
            field=models.TextField(default='NA', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='NA', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.TextField(default='NA', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.TextField(default='NA', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.TextField(default='NA', null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='address',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='city',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='department',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='designation',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='listing_date',
            field=models.DateTimeField(blank=True, default='NA', null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='password',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='phone',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='plan_id',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='pub_id',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='role',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='state',
            field=models.CharField(default='NA', max_length=255),
        ),
    ]
