# Generated by Django 5.0.7 on 2024-08-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_location_country_alter_location_dist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='property_type',
            field=models.CharField(choices=[('Commercial', 'Commercial'), ('Residential', 'Residential')], default='Commercial', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='sub_area',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='sub_category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='website',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='PropertyType',
        ),
        migrations.DeleteModel(
            name='SubArea',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
        migrations.DeleteModel(
            name='Website',
        ),
    ]
