# Generated by Django 5.0.7 on 2024-08-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_project_category_alter_location_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='construction_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Commercial', 'Commercial'), ('Residential', 'Residential')], default='Complete', max_length=50),
        ),
    ]
