# Generated by Django 5.0.7 on 2024-08-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_project_construction_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Under Processing', 'Under Processing'), ('Under Construction', 'Under Construction'), ('Complete', 'Complete')], default='Complete', max_length=50),
        ),
    ]
