# Generated by Django 4.1.13 on 2024-07-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='shareholderPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('month', models.CharField(max_length=25)),
                ('pdf', models.FileField(upload_to='shareholderPattern/')),
            ],
        ),
    ]
