# Generated by Django 4.1.13 on 2024-07-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_shareholderpattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='compliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fy', models.CharField(max_length=15)),
                ('quarter', models.CharField(max_length=25)),
                ('pdf', models.FileField(upload_to='compliance/')),
            ],
        ),
    ]
