# Generated by Django 4.1.13 on 2024-07-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_compliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliance',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
