# Generated by Django 4.1.13 on 2024-07-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_compliance_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliance',
            name='comp_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
