# Generated by Django 5.0.7 on 2024-07-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_projecttable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttable',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to='project_image2/'),
        ),
        migrations.AlterField(
            model_name='projecttable',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to='project_image3/'),
        ),
        migrations.AlterField(
            model_name='projecttable',
            name='image4',
            field=models.FileField(blank=True, null=True, upload_to='project_image4/'),
        ),
        migrations.AlterField(
            model_name='projecttable',
            name='master_plan',
            field=models.FileField(blank=True, null=True, upload_to='master_plans/'),
        ),
        migrations.AlterField(
            model_name='projecttable',
            name='unit_plan',
            field=models.FileField(blank=True, null=True, upload_to='unit_plans/'),
        ),
    ]
