# Generated by Django 5.0.7 on 2024-07-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_projecttable_image2_alter_projecttable_image3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttable',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
