# Generated by Django 5.0.7 on 2024-07-23 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_initial'),
        ('myapp', '0012_callback'),
    ]

    operations = [
        migrations.CreateModel(
            name='demoProject',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.project')),
                ('price2', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            bases=('api.project',),
        ),
    ]
