# Generated by Django 5.0.7 on 2024-07-24 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0011_remove_project_price'),
        ('myapp', '0014_delete_callback_delete_compliance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25)),
                ('country', models.CharField(default='', max_length=50)),
                ('mobile', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=100)),
                ('confirm', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='compliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fy', models.CharField(default='', max_length=15)),
                ('comp_type', models.CharField(default='', max_length=50, null=True)),
                ('quarter', models.CharField(default='', max_length=25)),
                ('description', models.CharField(default='', max_length=200, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='compliance/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default='', max_digits=10)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='projectEnquary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=50)),
                ('lastName', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('country', models.CharField(default='', max_length=50)),
                ('cityName', models.CharField(default='', max_length=50)),
                ('mobile', models.CharField(default='', max_length=50)),
                ('projectName', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='schedulOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=50)),
                ('lastName', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('country', models.CharField(default='', max_length=50)),
                ('mobile', models.CharField(default='', max_length=50)),
                ('schedule_data', models.CharField(default='', max_length=30)),
                ('schedule_time', models.CharField(default='', max_length=15)),
                ('projectName', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='shareholderPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='', max_length=10)),
                ('month', models.CharField(default='', max_length=25)),
                ('pdf', models.FileField(blank=True, default='', null='', upload_to='shareholderPattern/')),
            ],
        ),
        migrations.CreateModel(
            name='projectTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(default='', max_length=50)),
                ('locality', models.CharField(default='', max_length=50)),
                ('topology', models.CharField(default='', max_length=50)),
                ('location', models.CharField(default='', max_length=250)),
                ('neighbourhood', models.CharField(default='', max_length=50)),
                ('master_plan', models.FileField(blank=True, null=True, upload_to='master_plans/')),
                ('unit_plan', models.FileField(blank=True, null=True, upload_to='unit_plans/')),
                ('image', models.FileField(upload_to='project_image/')),
                ('image2', models.FileField(blank=True, null=True, upload_to='project_image2/')),
                ('image3', models.FileField(blank=True, null=True, upload_to='project_image3/')),
                ('image4', models.FileField(blank=True, null=True, upload_to='project_image4/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='api.project')),
            ],
        ),
    ]
