# Generated by Django 5.0.7 on 2024-07-25 09:00

import django.db.models.deletion
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_delete_apikey'),
        ('myapp', '0015_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callback',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='projectenquary',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulon',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        
    ]
