# Generated by Django 5.0.7 on 2024-07-25 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_delete_apikey'),
        ('myapp', '0016_callback_created_at_projectenquary_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='amenities/None/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities_set', to='api.project')),
            ],
        ),
    ]
