# Generated by Django 5.0.7 on 2024-08-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_posts_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='postImage/'),
        ),
    ]
