# Generated by Django 5.0.7 on 2024-08-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_posts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
