# Generated by Django 5.0.7 on 2024-08-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_posts_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
