# Generated by Django 5.0.7 on 2024-08-06 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_posts_pdf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='posts',
        ),
    ]
