# Generated by Django 5.0.7 on 2024-08-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_delete_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='posts/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='posts/')),
                ('post_data', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
