# Generated by Django 5.0.7 on 2024-08-06 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='post_data',
            new_name='post_date',
        ),
    ]
