# Generated by Django 5.0.7 on 2024-08-14 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_chatboatdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenities',
            name='project',
        ),
        migrations.DeleteModel(
            name='Callback',
        ),
        migrations.DeleteModel(
            name='chatboatData',
        ),
        migrations.DeleteModel(
            name='compliance',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
        migrations.DeleteModel(
            name='posts',
        ),
        migrations.DeleteModel(
            name='projectEnquary',
        ),
        migrations.RemoveField(
            model_name='projecttable',
            name='project',
        ),
        migrations.DeleteModel(
            name='schedulOn',
        ),
        migrations.DeleteModel(
            name='shareholderPattern',
        ),
        migrations.DeleteModel(
            name='amenities',
        ),
        migrations.DeleteModel(
            name='customer',
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
        migrations.DeleteModel(
            name='projectTable',
        ),
    ]
