# Generated by Django 5.0.7 on 2024-08-14 07:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0025_initial'),
        ('myapp', '0032_remove_amenities_project_delete_callback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25)),
                ('country', models.CharField(default='', max_length=50)),
                ('mobile', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=100)),
                ('confirm', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='chatboatData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='compliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fy', models.CharField(default='', max_length=15)),
                ('comp_type', models.CharField(default='', max_length=50, null=True)),
                ('quarter', models.CharField(default='', max_length=25)),
                ('description', models.CharField(default='', max_length=200, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='compliance/')),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('mobile', models.CharField(blank=True, max_length=18, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid mobile number.')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('countryName', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='posts/image/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='posts/pdf/')),
                ('post_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='projectEnquary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=50)),
                ('lastName', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('country', models.CharField(default='', max_length=50)),
                ('cityName', models.CharField(default='', max_length=50)),
                ('mobile', models.CharField(default='', max_length=50)),
                ('projectName', models.CharField(default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='schedulOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=50)),
                ('lastName', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('country', models.CharField(default='', max_length=50)),
                ('mobile', models.CharField(default='', max_length=50)),
                ('schedule_data', models.CharField(default='', max_length=30)),
                ('schedule_time', models.CharField(default='', max_length=15)),
                ('projectName', models.CharField(default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='shareholderPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='', max_length=10)),
                ('month', models.CharField(default='', max_length=25)),
                ('pdf', models.FileField(blank=True, default='', null='', upload_to='shareholderPattern/')),
            ],
        ),
        migrations.CreateModel(
            name='amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='amenities/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities_set', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='projectTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(default='', max_length=50)),
                ('locality', models.CharField(default='', max_length=50)),
                ('topology', models.CharField(default='', max_length=50)),
                ('location', models.CharField(default='', max_length=250)),
                ('neighbourhood', models.CharField(default='', max_length=50)),
                ('master_plan', models.FileField(blank=True, null=True, upload_to='master_plans/')),
                ('unit_plan', models.FileField(blank=True, null=True, upload_to='unit_plans/')),
                ('image', models.FileField(upload_to='project_image/')),
                ('image2', models.FileField(blank=True, null=True, upload_to='project_image2/')),
                ('image3', models.FileField(blank=True, null=True, upload_to='project_image3/')),
                ('image4', models.FileField(blank=True, null=True, upload_to='project_image4/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='api.project')),
            ],
        ),
    ]
