# Generated by Django 5.0.7 on 2024-08-14 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_initial'),
        ('myapp', '0033_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttable',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.location'),
        ),
    ]
