# Generated by Django 5.0.7 on 2024-08-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_alter_projecttable_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='sitevisiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(default='Unknown', max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
