# Generated by Django 5.0.7 on 2024-08-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_sitevisiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisiter',
            name='name',
            field=models.CharField(blank=True, default='Unknown', max_length=20, null=True),
        ),
    ]
