# Generated by Django 5.0.7 on 2024-08-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_sitevisiter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisiter',
            name='csrftoken',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
