# Generated by Django 5.0.7 on 2024-08-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_sitevisiter_csrftoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='membershipOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('offerPer', models.BigIntegerField()),
                ('price', models.BigIntegerField()),
                ('other', models.CharField(max_length=200)),
                ('validTill', models.DateTimeField()),
                ('image', models.FileField(upload_to='offerImage')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
