# Generated by Django 5.0.7 on 2024-08-21 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_membershipoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=10)),
                ('units', models.BigIntegerField()),
                ('email', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
            ],
        ),
    ]
