# Generated by Django 5.0.7 on 2024-08-22 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_blog_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='searchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searches', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('url', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, default='Unknown', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.sitevisiter')),
            ],
        ),
    ]
