# Generated by Django 5.0.7 on 2024-08-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_searchhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectCallus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('countryName', models.CharField(max_length=50)),
                ('countryCode', models.CharField(max_length=10)),
                ('mobile', models.BigIntegerField()),
                ('projectName', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
