# Generated by Django 5.0.7 on 2024-08-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_projectcallus_city_alter_projectcallus_countrycode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='blogs/'),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='blogs/'),
        ),
        migrations.AlterField(
            model_name='membershipoffer',
            name='image',
            field=models.FileField(upload_to='offerImage/'),
        ),
    ]
