# Generated by Django 5.0.7 on 2024-08-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_alter_blog_image_alter_blog_post_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttable',
            name='location',
        ),
        migrations.AlterField(
            model_name='projecttable',
            name='neighbourhood',
            field=models.CharField(default='Best Location in Your City', max_length=100),
        ),
    ]
