# Generated by Django 5.0.7 on 2024-08-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_remove_projecttable_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitevisiter',
            name='csrftoken',
        ),
        migrations.AddField(
            model_name='sitevisiter',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sitevisiter',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sitevisiter',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
