# Generated by Django 5.0.7 on 2024-08-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_remove_sitevisiter_csrftoken_sitevisiter_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevisiter',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
